title: Shadohub
lang: en-US
description: This site is meant to be for sharing my daily discoveries in the vast land of technology, as I dive deeper into Linux, C and Haskell languages, Emacs+Vim, and low level (closer to binary) exploitation/reversing.

edit: true

copyright:
  revision: true
# logo: assets/images/logo.png

addons:
  - github
  - gems
  - analytics
addons_branch: false

rougify: github

theme: null # disable pages default theme

# use front matter sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

# fluid: true

## -- Copyright -- ##
author: "Shadorain"
copyright: 
  since: 2020
  revision: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Shadorain"

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - deps.sh
  - CODE_OF_CONDUCT.md
  - LICENSE
  - requirements.txt
  - jekyll-rtd-theme.gemspec
  - README.md
